from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
INDEX=ROOT/'index.html'
SCRIPT='''<script>(()=>{const T={ar:{s1:'عام التأسيس في الدمام',s2:'افتتاح فرع الأحساء',s3:'مواقع رئيسية للمواد الغذائية',b1:'الفرع الرئيسي',b2:'منذ 2018',t1:'بداية الشركة — الدمام',p1:'انطلاق النشاط في بيع المواد الغذائية بالجملة.',t2:'أنشطة البلاستيك والحلويات',p2:'تأسست أنشطة مستقلة تحت مظلة الشركة لتخدم أسواقًا ومنتجات مختلفة.',t3:'افتتاح فرع الأحساء',p3:'افتتاح فرع الأحساء واستمرار التوسع في الأنشطة التجارية.',cap:'تجارة وتوزيع بالجملة',foot:'لبيع المواد الغذائية بالجملة · المملكة العربية السعودية'},en:{s1:'Founded in Dammam',s2:'Al-Ahsa Branch Opened',s3:'Main Food Product Locations',b1:'MAIN BRANCH',b2:'SINCE 2018',t1:'Company Founded — Dammam',p1:'Wholesale food trading became the company’s core activity.',t2:'Plastics, Sweets & Snacks',p2:'Independent activities were established under the company to serve different markets and product categories.',t3:'Al-Ahsa Branch Opened',p3:'The Al-Ahsa branch opened and the company continued expanding its commercial activities.',cap:'Wholesale Trade & Distribution',foot:'Wholesale Food Trading · Kingdom of Saudi Arabia'}};const q=(s,v)=>{const e=document.querySelector(s);if(e)e.textContent=v};const apply=()=>{const t=T[document.documentElement.lang==='en'?'en':'ar'];q('.stat:nth-child(1) small',t.s1);q('.stat:nth-child(2) small',t.s2);q('.stat:nth-child(3) small',t.s3);q('.branch:nth-child(1) .branch-label',t.b1);q('.branch:nth-child(2) .branch-label',t.b2);q('.timeline .event:nth-child(1) h4',t.t1);q('.timeline .event:nth-child(1) p',t.p1);q('.timeline .event:nth-child(2) h4',t.t2);q('.timeline .event:nth-child(2) p',t.p2);q('.timeline .event:nth-child(3) h4',t.t3);q('.timeline .event:nth-child(3) p',t.p3);q('.caption',t.cap);q('.footer-in div+div',t.foot)};apply();new MutationObserver(apply).observe(document.documentElement,{attributes:true,attributeFilter:['lang']})})();</script>'''
html=INDEX.read_text(encoding='utf-8')
if 'i18n-extra-marker' not in html:
    html=html.replace('</body>','<meta name="i18n-extra-marker" content="full-page">'+SCRIPT+'</body>',1)
INDEX.write_text(html,encoding='utf-8')
